@startuml Manage Hospital (PUT)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Hospital (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hospitals" as routerHospitals
participant "<<controllers>>\n:hospitals" as controllersHospitals
participant "<<model>>\n:Hospital" as modelHospital
database "<<MongoDB>>\n:hospitals" as HospitalsDatabase

client->server ++:req.put('/hospitals/:id')
server->routerHospitals ++:app.use('/hospitals',hospitals)
routerHospitals -> controllersHospitals ++:updateHospital(req, res)
controllersHospitals->modelHospital ++:updateHospital(req.params.id, req.body)
modelHospital ->HospitalsDatabase ++: findByIdAndUpdate(req.params.id, req.body)
HospitalsDatabase --> modelHospital --: updatedHospital
controllersHospitals <-- modelHospital --:updatedHospital
controllersHospitals->client --:response

@enduml